stages:
  - build
  - push

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/backend"  # Base image name
  IMAGE_TAG: "latest"  # Tag for the image
  FULL_IMAGE_PATH: "$DOCKER_IMAGE:$IMAGE_TAG"  # Full image path with tag

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build_backend:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $FULL_IMAGE_PATH -f backend/Dockerfile .

push_backend:
  stage: push
  tags:
    - docker
  script:
    - docker push $FULL_IMAGE_PATH

