stages:
  - build
  - push

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/backend"  # Base image name
  IMAGE_TAG: "latest"  # Tag for the image
  FULL_IMAGE_PATH: "$DOCKER_IMAGE:$IMAGE_TAG"  # Full image path with tag

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build_services:
  stage: build
  tags:
    - docker
  script:
    # Build all services with a `build` section in docker-compose.yml
    - docker-compose build

push_services:
  stage: push
  tags:
    - docker
  script:
    # Push all built images to the registry
    - docker-compose push
