stages:
  - build
  - push

variables:
  IMAGE_TAG: "latest"
  COMPOSE_PROJECT_NAME: "sports_project"

before_script:
  # Log in to the GitLab Container Registry
  - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build_services:
  stage: build
  tags:
    - docker
  script:
    # Build all services with a `build` section
    - docker-compose build

push_services:
  stage: push
  tags:
    - docker
  script:
    # Push all images with an `image` tag to the registry
    - docker-compose push
