stages:
  - build
  - deploy

variables:
  IMAGE_TAG: "latest"
  COMPOSE_PROJECT_NAME: "my_project"  # Replace with a unique name for the registry

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

# Build and Push All Custom Images
build_services:
  stage: build
  tags:
    - docker
  only:
    - main  # Trigger this job only on merges/commits to the main branch
  script:
    - docker-compose build
    - docker-compose push
