services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  spark-master:
    image: bitnami/spark:3.5.3
    hostname: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - kafka_network

  spark-worker:
    image: bitnami/spark:3.5.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - kafka_network

  hadoop:
    image: apache/hadoop:3.3.6
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - kafka_network
      
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: git.ecdf.ed.ac.uk:5050/sdol2425/duncan-proctor/sports_project/backend:latest
    depends_on:
      - zookeeper
      - kafka
      - spark-master
      - hadoop
    environment:
      KAFKA_BROKER_URL: kafka:9092
      SPARK_MASTER_URL: spark://spark-master:7077
      HADOOP_URL: hdfs://hadoop:9000
    entrypoint: ["wait-for-it.sh", "kafka:9092", "--", "uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
